### ISSUE TITLE
WorkLog of Sprint 1

### ISSUE THREAD

**Issue by metchanthou** [pnc-virtual-company/2021-G7-VC2-PART2#15]

**Comment by chanrychhoy** [comment]
[Chanry Chhoy_Work Log.xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7762798/Chanry.Chhoy_Work.Log.xlsx)
This is my work log for the first week.

**Comment by sophorneng** [comment]
[sophorn_worklog.xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7762997/sophorn_worklog.xlsx)
This is my worklog

**Comment by Som-Chhorn** [comment]
[Som Chhorn.xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7763573/Som.Chhorn.xlsx)
This is my worklog for first sprint

**Comment by dyna2002chhan** [comment]
[Dyna.chhan.Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7763764/Dyna.chhan.Worklog.Template.xlsx)
Here is my worklog for the first sprint. Thank you!

**Comment by lanhphalla** [comment]
[Worklog Template Week1.xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7764151/Worklog.Template.Week1.xlsx)
This is my worklog for week one iteration one.

**Comment by lanhphalla** [comment]
#
[Worklog Template Week1(Lanh-PHALLA).xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7764169/Worklog.Template.Week1.Lanh-PHALLA.xlsx)
This is my worklog of iteration one week one.

**Comment by metchanthou** [comment]
[Chanthou_Met-Work Log.xlsx](https://github.com/pnc-virtual-company/2021-G7-VC2-PART2/files/7770172/Chanthou_Met-Work.Log.xlsx)
This is my work log for the first sprint. Thank you, teacher.
Sorry teacher, I'm late sending my work log because I have a problem with the code, and I need to fix it quickly.
